bias_param_names_vary: []
cosmo_param_names_vary:
- omega_cold
- sigma8_cold
- hubble
- ns
- omega_baryon
data_mode: muchisimocks
evaluate_mean: true
idxs_obs: null
kwargs_data:
  tag_datagen: ''
mcmc_framework: dynesty
n_rlzs_per_cosmo: 1
tag_biasparams: _b1000_p0_n1
tag_data: _muchisimocks_quijote_p0_n1000_b1000_p0_n1_boxsize1000_nrlzs1_noiseless
tag_datagen: ''
tag_errG: _boxsize1000
tag_inf: _muchisimocks_quijote_p0_n1000_b1000_p0_n1_boxsize1000_nrlzs1_noiseless_pvary5_bvary0
tag_noiseless: ''
tag_params: _quijote_p0_n1000
