data_mode: muchisimocksPk
evaluate_mean: true
idxs_obs: null
kwargs_data_test:
  tag_datagen: ''
n_rlzs_per_cosmo: 1
n_train: 500
sweep_name: sbi-rand10
tag_biasparams: _biaszen_p4_n100000
tag_biasparams_test: _b1000_p0_n1
tag_data_test: _muchisimocksPk_quijote_p0_n1000_b1000_p0_n1
tag_data_train: _muchisimocksPk_p5_n10000_biaszen_p4_n100000
tag_inf_train: _muchisimocksPk_p5_n10000_biaszen_p4_n100000_ntrain500_best-sbi-rand10
tag_params: _p5_n10000
tag_params_test: _quijote_p0_n1000
tag_test: _TRAIN_muchisimocksPk_p5_n10000_biaszen_p4_n100000_ntrain500_best-sbi-rand10_TEST_muchisimocksPk_quijote_p0_n1000_b1000_p0_n1_mean
