data_mode: muchisimocksPk
evaluate_mean: false
kwargs_data:
  tag_datagen: ''
n_rlzs_per_cosmo: 1
n_train: 1000
run_mode: best
sweep_name: sbi-rand10
tag_biasparams: _biaszen_p4_n100000
tag_data: _muchisimocksPk_p5_n10000_biaszen_p4_n100000
tag_inf: _muchisimocksPk_p5_n10000_biaszen_p4_n100000_ntrain1000_best-sbi-rand10
tag_params: _p5_n10000
