data_mode: muchisimocks
evaluate_mean: false
kwargs_data:
  tag_datagen: ''
n_rlzs_per_cosmo: 1
n_train: 1000
run_mode: best
statistics:
- bispec
sweep_name: sbi-rand10
tag_biasparams: _biaszen_p4_n10000
tag_data: _muchisimocks_bispec_p5_n10000_biaszen_p4_n10000
tag_inf: _muchisimocks_bispec_p5_n10000_biaszen_p4_n10000_ntrain1000_best-sbi-rand10
tag_params: _p5_n10000
