data_mode: muchisimocks
kwargs_data:
  tag_datagen: ''
n_rlzs_per_cosmo: 1
n_train: 500
run_mode: single
statistics:
- pk
sweep_name: null
tag_biasparams: _biaszen_p4_n10000
tag_data: _muchisimocks_pk_p5_n10000_biaszen_p4_n10000
tag_inf: _muchisimocks_pk_p5_n10000_biaszen_p4_n10000_ntrain500
tag_params: _p5_n10000
