data_mode: muchisimocks
kwargs_data:
  tag_datagen: ''
n_rlzs_per_cosmo: 1
n_train: 10000
run_mode: best
statistics:
- pk
sweep_name: _muchisimocks_pk_p5_n10000_biaszen_p4_n100000_ntrain10000_best-sbi-rand10_rand10
tag_biasparams: _biaszen_p4_n100000
tag_data: _muchisimocks_pk_p5_n10000_biaszen_p4_n100000
tag_inf: _muchisimocks_pk_p5_n10000_biaszen_p4_n100000_ntrain10000_best-sbi-rand10
tag_params: _p5_n10000
