data_mode: muchisimocks
kwargs_data:
  tag_datagen: ''
n_rlzs_per_cosmo: 1
n_train: 1000
run_mode: single
statistics:
- pk
sweep_name: null
tag_biasparams: _biaszen_p4_n50000
tag_data: _muchisimocks_pk_p5_n10000_biaszen_p4_n50000
tag_inf: _muchisimocks_pk_p5_n10000_biaszen_p4_n50000_ntrain1000
tag_params: _p5_n10000
